/**
 * 48 keywords that are automatically flagged for admin moderation.
 * Posts containing any of these (case-insensitive) appear in the CRM "Flagged" tab.
 * Replace the placeholder entries below with your actual list of abusive/bad terms.
 */
const MODERATION_KEYWORDS = [
  'replace_1',
  'replace_2',
  'replace_3',
  'replace_4',
  'replace_5',
  'replace_6',
  'replace_7',
  'replace_8',
  'replace_9',
  'replace_10',
  'replace_11',
  'replace_12',
  'replace_13',
  'replace_14',
  'replace_15',
  'replace_16',
  'replace_17',
  'replace_18',
  'replace_19',
  'replace_20',
  'replace_21',
  'replace_22',
  'replace_23',
  'replace_24',
  'replace_25',
  'replace_26',
  'replace_27',
  'replace_28',
  'replace_29',
  'replace_30',
  'replace_31',
  'replace_32',
  'replace_33',
  'replace_34',
  'replace_35',
  'replace_36',
  'replace_37',
  'replace_38',
  'replace_39',
  'replace_40',
  'replace_41',
  'replace_42',
  'replace_43',
  'replace_44',
  'replace_45',
  'replace_46',
  'replace_47',
  'replace_48',
];

module.exports = { MODERATION_KEYWORDS };
